# Generated by Django 5.2 on 2025-09-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceprediction',
            unique_together={('product', 'season', 'predicted_by')},
        ),
    ]
